"""Eight ways the database the migrations build is not the one the models describe.

P2 row 18; DATA-02, DATA-03, DATA-04, DATA-05, DATA-07, DATA-08, DATA-09, DATA-11.

The tests build their schema with `Base.metadata.create_all`; production builds it
with Alembic. Where those two disagree, every test in the suite is exercising a
database that does not exist, and the divergence is invisible from either side.

- **DATA-05** — `audit_logs` is missing from `app/models/__init__.py`, so it is not in
  the metadata Alembic autogenerates against. The next autogenerated revision would
  emit `drop_table("audit_logs")` — the table the security work added specifically to
  make sensitive auth actions durable.
- **DATA-11** — `ix_code_graph_symbols_cluster` exists in a migration and in no model,
  so it is absent from every `create_all` schema.
- **DATA-03** — `db_index.row_count` is a 32-bit `Integer` fed from `reltuples::bigint`
  and ClickHouse `total_rows` (UInt64). The connectors deliberately widen to 64 bits
  on the way in and nothing clamps in between.
- **DATA-07** — the model renders one unique index on `mcp_api_keys.token_hash`; the
  migration declares a `UniqueConstraint` *and* a plain index under the same name. So
  production carries two btree indexes on one 64-char column, and the object named
  `ix_mcp_api_keys_token_hash` means different things in the two schemas.
- **DATA-08** — `uq_error_log_project_sig` is a unique index over a nullable column,
  and both engines treat NULLs as distinct — so the dedup rule imposes nothing at all
  on system-scoped errors. The project already solved this one table over, with
  `coalesce(connection_id, '')`.
- **DATA-09** — the `doc_embeddings` expression index covers `source_path` while the
  delete path filters `source_path OR path`, so PostgreSQL cannot build a `BitmapOr`
  and scans the project.
- **DATA-04** — the schema has zero `CHECK` constraints, and `indexing_runs.status` is
  the predicate of the single-active-run guard: the partial unique index is scoped by
  a literal list of three strings, so a fourth value silently escapes it.
- **DATA-02** — 81 columns are `NOT NULL` in the model and nullable in the schema the
  migrations build.
"""

from __future__ import annotations

import pathlib

import pytest
from sqlalchemy import BigInteger

from app.models.base import Base


class TestEveryTableIsInTheMetadata:
    """DATA-05."""

    def test_audit_logs_is_reachable_from_the_package(self) -> None:
        import app.models as models_pkg

        source = pathlib.Path(models_pkg.__file__).read_text(encoding="utf-8")
        assert "audit_log" in source, (
            "`alembic/env.py` reads `Base.metadata`, and that is populated by whatever "
            "`app/models/__init__.py` imports. It imports 48 models and omits exactly "
            "one — `audit_log`, which is otherwise imported only inside a function "
            "body. The next autogenerated revision would emit drop_table('audit_logs') "
            "(DATA-05)"
        )

    def test_the_table_is_in_the_metadata_after_a_bare_import(self) -> None:
        """The metadata, not the import line — an import that is never executed at
        module scope leaves the table absent all the same."""
        import app.models  # noqa: F401

        assert "audit_logs" in Base.metadata.tables, (
            "the table is not in the metadata Alembic compares against"
        )


class TestTheModelDescribesEveryIndex:
    """DATA-11."""

    def test_the_cluster_index_is_on_the_model(self) -> None:
        from app.models.code_graph import CodeGraphSymbol

        names = {ix.name for ix in CodeGraphSymbol.__table__.indexes}
        assert "ix_code_graph_symbols_cluster" in names, (
            "the clustering migration adds this index and the model — the only "
            "description of the table that `create_all` and the test suite ever "
            f"read — does not carry it. Declared: {sorted(names)} (DATA-11)"
        )


class TestAVendorRowCountFits:
    """DATA-03."""

    def test_row_count_is_64_bit(self) -> None:
        from app.models.db_index import DbIndex

        column = DbIndex.__table__.c.row_count
        assert isinstance(column.type, BigInteger), (
            "the connectors deliberately widen the vendor's estimate to 64 bits when "
            "reading it (`reltuples::bigint`, ClickHouse UInt64) and nothing clamps in "
            f"between, while the column that stores it is {column.type!r} — signed "
            "32-bit on PostgreSQL, max 2 147 483 647 (DATA-03)"
        )


class TestOneNameMeansOneThing:
    """DATA-07."""

    def test_the_token_hash_index_is_declared_once(self) -> None:
        migration = (
            pathlib.Path(__file__).parents[2].parent
            / "alembic"
            / "versions"
            / "d3e4f5g6h7i8_add_mcp_api_keys_table.py"
        )
        import ast

        tree = ast.parse(migration.read_text(encoding="utf-8"))
        # The CALL, not the name: the name now appears in a comment explaining why
        # the second index is gone, and a substring check matched that too.
        created = [
            ast.unparse(node)
            for node in ast.walk(tree)
            if isinstance(node, ast.Call)
            and "create_index" in ast.unparse(node.func)
            and "token_hash" in ast.unparse(node)
        ]
        assert not created, (
            "the migration declares a UniqueConstraint (which brings its own implicit "
            "index) AND a plain create_index under the very name the model uses for "
            "its unique one. Production carries two btree indexes on one 64-char "
            "column, and the object named ix_mcp_api_keys_token_hash means different "
            f"things in the two schemas: {created} (DATA-07)"
        )


class TestDedupAppliesToSystemErrors:
    """DATA-08."""

    def test_the_unique_index_coalesces_the_nullable_column(self) -> None:
        from app.models.error_log import ErrorLog

        target = next(
            (ix for ix in ErrorLog.__table__.indexes if ix.name == "uq_error_log_project_sig"),
            None,
        )
        assert target is not None, "the dedup index is gone; this guard is blind"
        rendered = " ".join(str(e) for e in target.expressions)
        assert "coalesce" in rendered.lower(), (
            "`error_log.project_id` is nullable — system and span events carry no "
            "project — and both engines treat NULLs as distinct in a unique index, so "
            "the dedup rule imposes nothing at all on exactly those rows. The project "
            "solved this one table over: `uq_indexing_runs_active_one` indexes "
            f"coalesce(connection_id, ''). Rendered: {rendered} (DATA-08)"
        )

    @pytest.mark.asyncio
    async def test_the_upsert_survives_a_race(self) -> None:
        import inspect

        from app.services.error_log_service import ErrorLogService

        source = inspect.getsource(ErrorLogService.upsert)
        assert "IntegrityError" in source, (
            "`upsert` is a read-then-write with no IntegrityError handling, so on the "
            "non-NULL rows the unique constraint turns a race into a 500 rather than "
            "into a merge (DATA-08)"
        )


class TestTheDeletePathHasAnIndex:
    """DATA-09."""

    def test_both_metadata_keys_are_indexed(self) -> None:
        from app.models.doc_embedding import DocEmbedding

        rendered = " ".join(
            str(expression)
            for ix in DocEmbedding.__table__.indexes
            for expression in ix.expressions
        )
        assert "'path'" in rendered, (
            "the delete path filters `metadata ->> 'source_path' = %s OR metadata ->> "
            "'path' = %s`, and only the first key is indexed — so PostgreSQL cannot "
            f"build a BitmapOr and scans every row for the project. Indexed: {rendered} "
            "(DATA-09)"
        )


class TestTheStatusVocabularyIsEnforced:
    """DATA-04."""

    def test_indexing_run_status_has_a_check_constraint(self) -> None:
        from sqlalchemy import CheckConstraint

        from app.models.indexing_run import IndexingRun

        checks = [c for c in IndexingRun.__table__.constraints if isinstance(c, CheckConstraint)]
        assert checks, (
            "the schema has zero CHECK constraints, and this column's vocabulary is "
            "load-bearing: the partial unique index enforcing 'one active run per "
            "(project, kind, connection)' is scoped by a literal list of three status "
            "strings, so a fourth value escapes the guard entirely (DATA-04)"
        )
        rendered = " ".join(str(c.sqltext) for c in checks)
        for status in ("queued", "running", "cancelling", "completed", "failed"):
            assert status in rendered, f"{status!r} is missing from the vocabulary: {rendered}"


class TestNullabilityAgrees:
    """DATA-02."""

    def test_the_alignment_helper_can_name_the_divergence(self) -> None:
        from app.ops.schema_alignment import columns_requiring_not_null

        planned = columns_requiring_not_null()
        assert isinstance(planned, list)
        assert all(len(row) == 3 for row in planned), (
            "each row is (table, column, fill) — the fill is what a pre-existing NULL "
            "becomes, and a column with no answer to that question must not be "
            "silently skipped"
        )

    def test_it_reads_the_models_rather_than_a_hand_written_list(self) -> None:
        """81 columns across 19 tables is a list that goes stale the day it is written.

        The helper derives them from `Base.metadata`, so a table added next month is
        covered without anybody remembering this migration exists.
        """
        import inspect

        from app.ops import schema_alignment

        source = inspect.getsource(schema_alignment)
        assert "Base.metadata" in source, (
            "the column list is hand-written, so it is already out of date for every "
            "table created after it"
        )
