"""hardening_indexes_fk_constraints

Revision ID: 5f9fe870b98c
Revises: r3s4t5u6v7w8
Create Date: 2026-03-18 17:29:19.672625
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5f9fe870b98c'
down_revision: Union[str, None] = 'r3s4t5u6v7w8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_learning_summaries', schema=None) as batch_op:
        batch_op.alter_column('total_lessons',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('lessons_by_category_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('compiled_prompt',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('last_compiled_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('agent_learnings', schema=None) as batch_op:
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0.6'"))
        batch_op.alter_column('times_confirmed',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('times_applied',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_connection_id'), ['connection_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('code_db_sync', schema=None) as batch_op:
        batch_op.alter_column('code_columns_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('used_in_files_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('read_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('write_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('data_format_notes',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('column_sync_notes_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('business_logic_notes',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('conversion_warnings',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('query_recommendations',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('sync_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'unknown'"))
        batch_op.alter_column('confidence_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'3'"))
        batch_op.alter_column('synced_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('code_db_sync_summary', schema=None) as batch_op:
        batch_op.alter_column('total_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('synced_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('code_only_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('db_only_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('mismatch_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('global_notes',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('data_conventions',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('query_guidelines',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('sync_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'idle'"))
        batch_op.alter_column('synced_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('commit_index', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commit_index_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('custom_rules', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_custom_rules_project_id', 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('db_index', schema=None) as batch_op:
        batch_op.alter_column('table_schema',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               existing_server_default=sa.text("'public'"))
        batch_op.alter_column('column_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('sample_data_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('(true)'))
        batch_op.alter_column('relevance_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'3'"))
        batch_op.alter_column('business_description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('data_patterns',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('column_notes_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('column_distinct_values_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('query_hints',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('code_match_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'unknown'"))
        batch_op.alter_column('code_match_details',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('indexed_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('db_index_summary', schema=None) as batch_op:
        batch_op.alter_column('total_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('active_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('empty_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('orphan_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('phantom_tables',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('summary_text',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('recommendations',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('indexed_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('indexing_checkpoint', schema=None) as batch_op:
        batch_op.alter_column('completed_steps',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('changed_files_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('deleted_files_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('profile_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('knowledge_json',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('processed_doc_paths',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('total_docs',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('knowledge_docs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_docs_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('project_cache', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('project_invites', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_project_invites_project_id'), ['project_id'], unique=False)
        batch_op.create_unique_constraint('uq_invite_project_email_status', ['project_id', 'email', 'status'])

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('project_repositories', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('rag_feedback', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index(batch_op.f('ix_rag_feedback_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))

    with op.batch_alter_table('rag_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_feedback_project_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('project_repositories', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('project_members', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('project_invites', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invite_project_email_status', type_='unique')
        batch_op.drop_index(batch_op.f('ix_project_invites_project_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('project_cache', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('knowledge_docs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_docs_project_id'))

    with op.batch_alter_table('indexing_checkpoint', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('total_docs',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('processed_doc_paths',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('knowledge_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('profile_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('deleted_files_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('changed_files_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('completed_steps',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('db_index_summary', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('indexed_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('recommendations',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('summary_text',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('phantom_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('orphan_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('empty_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('active_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('db_index', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('indexed_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('code_match_details',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('code_match_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'unknown'"))
        batch_op.alter_column('query_hints',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('column_distinct_values_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('column_notes_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('data_patterns',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('business_description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('relevance_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'3'"))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('(true)'))
        batch_op.alter_column('sample_data_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('column_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('table_schema',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               existing_server_default=sa.text("'public'"))

    with op.batch_alter_table('custom_rules', schema=None) as batch_op:
        batch_op.drop_constraint('fk_custom_rules_project_id', type_='foreignkey')

    with op.batch_alter_table('commit_index', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commit_index_project_id'))

    with op.batch_alter_table('code_db_sync_summary', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('synced_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('sync_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'idle'"))
        batch_op.alter_column('query_guidelines',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('data_conventions',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('global_notes',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('mismatch_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('db_only_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('code_only_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('synced_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('total_tables',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('code_db_sync', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('synced_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('confidence_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'3'"))
        batch_op.alter_column('sync_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'unknown'"))
        batch_op.alter_column('query_recommendations',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('conversion_warnings',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('business_logic_notes',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('column_sync_notes_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('data_format_notes',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('write_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('read_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('used_in_files_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('code_columns_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_project_id'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_connection_id'))

    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))

    with op.batch_alter_table('agent_learnings', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('times_applied',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('times_confirmed',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('confidence',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0.6'"))

    with op.batch_alter_table('agent_learning_summaries', schema=None) as batch_op:
        batch_op.alter_column('last_compiled_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('compiled_prompt',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('lessons_by_category_json',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
        batch_op.alter_column('total_lessons',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
