"""Drop ``project_repositories.auth_token_encrypted`` — a dead encrypted column (F-REPO-04)

The column was declared on the model and accepted as a keyword by
``RepositoryService.create``, but **no caller ever passed it**, it was absent from
``ALLOWED_UPDATE_FIELDS``, and nothing read it. It was found by the F-CONN-05
derived-coverage test, which compares the rotation sweep's map against every mapped
column ending in ``_encrypted`` — an AST sweep for ``encrypt(`` calls could not see it,
precisely because nothing writes it.

A column shaped to hold secrets, with no writer and no reader, is not neutral: it is the
place the next feature stores a token without anyone reviewing how it got there. Bringing
it back is one migration, on the day HTTPS token auth is actually built.

Verified empty before dropping — production held **0 rows** in `project_repositories`
(``SELECT count(*), count(auth_token_encrypted)`` → ``0 | 0`` on 2026-08-25), so no
ciphertext is lost. Repositories authenticate through ``ssh_key_id``.

**Hand-written, not autogenerated, and that is load-bearing.** `alembic revision
--autogenerate` against the SQLite dev database produced 194 DDL operations for this
one-column change, including ``op.drop_table('audit_logs')`` — the durable auth audit
table added by F-AUTH-15. SQLite's introspection disagrees with the model metadata about
NOT NULL defaults and index naming, so autogenerate reads the difference as intent.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6287a47828ca"
down_revision: str | None = "d3e4f5a6b7c8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # batch_alter_table because SQLite cannot DROP COLUMN in place on older versions;
    # on PostgreSQL it compiles to a plain ALTER TABLE ... DROP COLUMN.
    with op.batch_alter_table("project_repositories", schema=None) as batch_op:
        batch_op.drop_column("auth_token_encrypted")


def downgrade() -> None:
    # Restores the column, not its contents — there were none to restore.
    with op.batch_alter_table("project_repositories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("auth_token_encrypted", sa.Text(), nullable=True))
