"""add_custom_rules

Revision ID: e12901fc4e99
Revises: cc9678c75544
Create Date: 2026-03-15 01:12:49.982993
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e12901fc4e99'
down_revision: Union[str, None] = 'cc9678c75544'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('custom_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_rules_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_rules_project_id'))

    op.drop_table('custom_rules')
    # ### end Alembic commands ###
